backend:
  name: git-gateway
  branch: master

media_folder: 'static/images/uploads'
public_folder: 'uploads'

collections:
  - name: 'project'
    label: 'Project'
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      # - { label: 'Order', name: 'order', widget: 'number', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          format: 'Do MMM YYYY',
        }
      - {
          label: 'Featured Image',
          name: 'featuredimage',
          widget: 'image',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
        }
      - {
          label: 'Featured Description',
          name: 'featureddescription',
          widget: 'markdown',
        }
      - label: 'Description'
        name: 'description'
        widget: 'list'
        fields:
          - { label: Description Text, name: descriptionText, widget: 'markdown' }
          - { label: Description Image, name: descriptionImage, widget: 'image', required: false }

  - name: 'pages'
    label: 'Pages'
    files:
      - file: 'content/pages/about'
        label: 'About Page'
        name: 'about'
        fields:
          - {
              label: 'Image',
              name: 'image',
              widget: 'image',
            }
          - label: 'Description'
            name: 'description'
            widget: 'list'
            fields:
              - { label: Description Text, name: descriptionText, widget: 'markdown' }
              - { label: Description Image, name: descriptionImage, widget: 'image', required: false }




