backend:
  name: git-gateway
  branch: master

media_folder: 'static/images/uploads'
public_folder: 'images/uploads'

collections:
  - name: 'project'
    label: 'Project'
    folder: 'content/projects'
    create: true
    slug: '{{slug}}'
    format: 'json'
    sort: "date:desc"
    fields:
      # - { label: 'Order', name: 'order', widget: 'number', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          format: 'Do MMM YYYY',
        }
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
        }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
        }
      - {
          label: 'Featured Description',
          name: 'description',
          widget: 'markdown',
        }
      - label: 'Body'
        name: 'body'
        widget: 'list'
        fields:
          - { label: 'Body Text', name: 'bodyText', widget: 'markdown' }
          - { label: 'BodyImage', name: 'bodyImage', widget: 'image', required: false }

  - name: 'page'
    label: 'Pages'
    folder: 'content/pages'
    create: true
    slug: '{{slug}}'
    format: 'json'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - {
          label: 'Feature Image',
          name: 'image',
          widget: 'image',
          required: false
        }
      - label: 'Body'
        name: 'body'
        widget: 'markdown'




